import '../../../core/money/money.dart';

/// Immutable debit/credit posting generated by a validated transaction.
class LedgerEntry {
  LedgerEntry({
    required this.accountId,
    required this.debit,
    required this.credit,
    required this.occurredAt,
    required this.description,
  }) : assert(
         debit.minorUnits >= 0 && credit.minorUnits >= 0,
         'Un débit et un crédit ne peuvent pas être négatifs.',
       ),
       assert(
         debit.minorUnits == 0 || credit.minorUnits == 0,
         'Une ligne ne peut pas être à la fois débitée et créditée.',
       );

  final String accountId;
  final Money debit;
  final Money credit;
  final DateTime occurredAt;
  final String description;

  Money get signedAmount => debit - credit;
}
