-- Strictly read-only independent postcheck for the TEST_FE_20260809 receipt.
with keys(test_name, idempotency_key) as (values
 ('cash','00000000-0000-4000-8000-000000000101'::uuid),('debt','00000000-0000-4000-8000-000000000102'::uuid),('debt_partial','00000000-0000-4000-8000-000000000103'::uuid),('debt_final','00000000-0000-4000-8000-000000000104'::uuid),('receivable','00000000-0000-4000-8000-000000000105'::uuid),('receivable_partial','00000000-0000-4000-8000-000000000106'::uuid),('receivable_final','00000000-0000-4000-8000-000000000107'::uuid),('recovery','00000000-0000-4000-8000-000000000108'::uuid),('recovery_partial','00000000-0000-4000-8000-000000000109'::uuid),('recovery_final','00000000-0000-4000-8000-000000000110'::uuid),('allocation','00000000-0000-4000-8000-000000000111'::uuid),('account_transfer','00000000-0000-4000-8000-000000000112'::uuid),('envelope_transfer','00000000-0000-4000-8000-000000000113'::uuid)),
events as (select keys.test_name,events.id from keys left join public.financial_events events on events.idempotency_key=keys.idempotency_key and events.description like 'TEST_FE_20260809%'),
counts as (select test_name,count(id) event_count,(array_agg(id order by id))[1] event_id from events group by test_name),
checks as (select
 (select event_count=1 from counts where test_name='cash') cash_once,
 (select count(*)=1 from public.financial_transactions where event_id=(select event_id from counts where test_name='cash')) cash_tx,
 (select count(*)=1 from public.obligations where origin_event_id=(select event_id from counts where test_name='debt')) debt,
 (select remaining_amount=0 from public.obligation_balances where origin_event_id=(select event_id from counts where test_name='debt')) debt_closed,
 (select count(*)=1 from public.obligations where origin_event_id=(select event_id from counts where test_name='receivable')) receivable,
 (select remaining_amount=0 from public.obligation_balances where origin_event_id=(select event_id from counts where test_name='receivable')) receivable_closed,
 (select count(*)=1 from public.obligations where origin_event_id=(select event_id from counts where test_name='recovery')) recovery,
 (select count(*)=1 from public.envelope_movements where event_id=(select event_id from counts where test_name='recovery_final') and movement_type='refund' and direction='inflow') refund,
 (select count(*)=1 from public.budget_funding_links where event_id=(select event_id from counts where test_name='allocation')) allocation_link,
 (select count(*)=0 from public.financial_transactions where event_id=(select event_id from counts where test_name='allocation')) allocation_no_tx,
 (select count(*)=1 from public.financial_transactions where event_id=(select event_id from counts where test_name='account_transfer')) account_transfer,
 (select count(*)=2 from public.envelope_movements where event_id=(select event_id from counts where test_name='envelope_transfer')) envelope_transfer,
 not exists(select 1 from public.financial_transactions transactions where transactions.event_id in(select event_id from counts where event_id is not null) and not exists(select 1 from public.financial_events events where events.id=transactions.event_id)) no_orphan_transactions,
 not exists(select 1 from public.envelope_movements movements where movements.event_id in(select event_id from counts where event_id is not null) and not exists(select 1 from public.financial_events events where events.id=movements.event_id)) no_orphan_movements,
 not exists(select 1 from public.financial_events events where events.description like 'TEST_FE_20260809%' and events.idempotency_key not in(select idempotency_key from keys)) scope_clean),
issues as (select 'event_cardinality' code,test_name detail from counts where event_count<>1 union all select 'cash','cash ledger transaction missing' where not coalesce((select cash_once and cash_tx from checks),false) union all select 'debt','debt creation or settlement inconsistent' where not coalesce((select debt and debt_closed from checks),false) union all select 'receivable','receivable creation or settlement inconsistent' where not coalesce((select receivable and receivable_closed from checks),false) union all select 'recovery','recovery/refund inconsistent' where not coalesce((select recovery and refund from checks),false) union all select 'allocation','allocation funding or non-bank rule inconsistent' where not coalesce((select allocation_link and allocation_no_tx from checks),false) union all select 'transfers','transfer rows incomplete' where not coalesce((select account_transfer and envelope_transfer from checks),false) union all select 'orphan','orphan financial or envelope row' where not coalesce((select no_orphan_transactions and no_orphan_movements from checks),false) union all select 'scope','unexpected tagged event' where not coalesce((select scope_clean from checks),false))
select not exists(select 1 from issues) business_postcheck_ready,(select count(*) from issues) blocking_issue_count,0 warning_count,
 (select count(*) from events where id is not null) financial_events_count,(select count(*) from public.financial_transactions where event_id in(select event_id from counts where event_id is not null)) financial_transactions_count,(select count(*) from public.financial_transaction_lines lines join public.financial_transactions transactions on transactions.id=lines.transaction_id where transactions.event_id in(select event_id from counts where event_id is not null)) financial_transaction_lines_count,(select count(*) from public.envelope_movements where event_id in(select event_id from counts where event_id is not null)) envelope_movements_count,(select count(*) from public.obligations where origin_event_id in(select event_id from counts where event_id is not null)) obligations_count,(select count(*) from public.obligation_settlements where event_id in(select event_id from counts where event_id is not null)) settlements_count,(select count(*) from public.budget_funding_links where event_id in(select event_id from counts where event_id is not null)) funding_links_count,coalesce((select jsonb_agg(jsonb_build_object('code',code,'detail',detail) order by code,detail) from issues),'[]'::jsonb) blocking_details,'[]'::jsonb warnings;
