enum ImportTemplateType { accounts, envelopes, expenses, revenues, advances, historicalBalances, goals }
class CsvImportTemplateDefinition { const CsvImportTemplateDefinition(this.type,this.id,this.label,this.description,this.fileName,this.columns,this.exampleRow,this.order); final ImportTemplateType type; final String id,label,description,fileName,exampleRow; final List<String> columns; final int order; String get header=>columns.join(';'); String get csvContent=>'$header\n$exampleRow\n'; }
const csvImportTemplates=<CsvImportTemplateDefinition>[
CsvImportTemplateDefinition(ImportTemplateType.accounts,'accounts','Comptes','Importer les comptes bancaires et espèces.','template_comptes.csv',['external_id','nom','type','titulaire','statut','solde_initial_centimes','date_solde_initial'],'EXEMPLE-001;Compte courant;banque;Ibrahim;actif;0;2026-01-01',1),
CsvImportTemplateDefinition(ImportTemplateType.envelopes,'envelopes','Enveloppes','Importer les enveloppes budgétaires.','template_enveloppes.csv',['external_id','nom','categorie','periode','montant_initial_centimes','statut'],'EXEMPLE-001;Courses;Alimentation;mensuelle;300000;actif',2),
CsvImportTemplateDefinition(ImportTemplateType.expenses,'expenses','Journal des dépenses','Importer les dépenses historiques ou courantes.','template_journal_depenses.csv',['external_id','date','libelle','montant_centimes','enveloppe','paye_par','saisi_par','compte_paiement','commentaire','historique_non_rapproche'],'EXEMPLE-001;2026-01-15;Courses hebdomadaires;45000;Courses;Ibrahim;Ibrahim;Compte Ibrahim CIH;Exemple;non',3),
CsvImportTemplateDefinition(ImportTemplateType.revenues,'revenues','Revenus','Importer les salaires, primes et autres revenus.','template_revenus.csv',['external_id','date','source','montant_centimes','beneficiaire','compte','commentaire'],'EXEMPLE-001;2026-01-31;Salaire;1310000;Ibrahim;Compte Ibrahim CIH;Exemple',4),
CsvImportTemplateDefinition(ImportTemplateType.advances,'advances','Avances','Importer les avances entre personnes et leurs remboursements.','template_avances.csv',['external_id','date','avance_par','pour_qui','montant_centimes','motif','statut','montant_rembourse_centimes'],'EXEMPLE-001;2026-01-10;Ibrahim;Nora;50000;Achat commun;ouverte;0',5),
CsvImportTemplateDefinition(ImportTemplateType.historicalBalances,'historical_balances','Soldes historiques','Importer les soldes de référence des comptes ou enveloppes.','template_soldes_historiques.csv',['external_id','date_reference','type_element','nom_element','solde_centimes','commentaire'],'EXEMPLE-001;2026-01-01;compte;Compte Ibrahim CIH;250000;Solde initial',6),
CsvImportTemplateDefinition(ImportTemplateType.goals,'goals','Objectifs','Importer les objectifs d’épargne et d’acquisition.','template_objectifs.csv',['external_id','nom','montant_cible_centimes','montant_initial_centimes','date_cible','priorite','statut'],'EXEMPLE-001;Voiture;18000000;3652075;2030-12-31;haute;actif',7),];
CsvImportTemplateDefinition byType(ImportTemplateType type)=>csvImportTemplates.firstWhere((x)=>x.type==type);
CsvImportTemplateDefinition? byId(String id){for(final x in csvImportTemplates){if(x.id==id)return x;}return null;}
